{% set name = "aioretry" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aioretry-{{ version }}.tar.gz
  sha256: 5a65210119630c42c0662581a742dd25b45420e674bad36d4d8b1442c38e51d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - aioretry
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/kaelzhang/python-aioretry
  summary: 'Asyncio retry utility for Python 3.7+'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/kaelzhang/python-aioretry

extra:
  recipe-maintainers:
    - kaelzhang
